image:
  name: golang:1.12.1
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
variables:
  GO111MODULE: 'on'
  GOOS: 'linux'
  GOARCH: 'amd64'

stages:
  - build_binary
  - build_docker

# This builds and tests the binary prior to building an image.
build_binary:
  stage: build_binary
  image: golang:1.12.1
  before_script:
    - cd $GOPATH/src
    - mkdir -p github.com/grab
    - cd github.com/grab
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
  script:
    - go test ./...
    - go build .
  artifacts:
    untracked: true
    paths:
      - talaria
  only:
    refs:
      - merge_requests
      - master

# This builds a docker for the merge request. The docker image can be fetched under 'talariadb/db:testing' tag.
build_docker_mr:
  stage: build_docker
  image: docker:stable
  dependencies: 
    - build_binary
  services:
    - docker:dind
  tags:
    - docker
  script:
    - docker build . --build-arg GO_BINARY=talaria -t="talariadb/db:testing"
    - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
    - docker push talariadb/db:testing
  only:
    refs:
      - merge_requests

# This builds the final docker image that can be deployed. It creates 'talariadb/db:latest' and 'talariadb/db:$COMMIT' tags.
build_docker:
  stage: build_docker
  image: docker:stable
  dependencies: 
    - build_binary
  services:
    - docker:dind
  tags:
    - docker
  script:
    - docker build . --build-arg GO_BINARY=talaria  -t="talariadb/db:$CI_COMMIT_SHORT_SHA" -t="talariadb/db:latest"
    - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
    - docker push talariadb/db:$CI_COMMIT_SHORT_SHA
    - docker push talariadb/db:latest
  only:
    refs:
      - master
